server:
    port: 9004
spring:
    application:
        name: tensquare_article
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.229.128:3306/tensquare_article?characterEncoding=utf-8&useSSL=false
        username: root
        password: root
    jpa:
        show-sql: true
        database: mysql
    redis:
        host: 192.168.229.128